apiVersion: v1
kind: Service
metadata:
  labels:
    app: loi-service
  name: loi-service
  namespace: uat01
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: loi-service

