apiVersion: v1
kind: Service
metadata:
  labels:
    app: browsing-ui
  name: browsing-ui
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 4000
      targetPort: 8080
  selector:
    app: browsing-ui
