apiVersion: v1
kind: Service
metadata:
  labels:
    app: script-executor
  name: script-executor
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9016
      targetPort: 8080
  selector:
    app: script-executor
