apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-cleansing-ui
  name: data-cleansing-ui
  namespace: uat01 
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8080
  selector:
    app: data-cleansing-ui
