apiVersion: v1
kind: Service
metadata:
  name: postgresql-db
  namespace: primecloud
  labels:
    app: postgresql-db
spec:
  type: ClusterIP 
  ports:
  - port: 9400
    targetPort: 5432
  selector:
    app: postgresql-db
