apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pgadmin
  name: pgadmin
  namespace: primecloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          imagePullPolicy: Always
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: pkurra@alveotech.com 
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin
            - name: PGADMIN_DISABLE_POSTFIX
              value: "true"
          ports:
            - containerPort: 80
      restartPolicy: Always
