apiVersion: v1
kind: Service
metadata:
  labels:
    app: operations-board-ui
  name: operations-board-ui
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: operations-board-ui
