apiVersion: v1
kind: Service
metadata:
  labels:
    app: ac-dl-read
  name: ac-dl-read
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 9009
      targetPort: 9000
  selector:
    app: ac-dl-read
