apiVersion: v1
kind: Service
metadata:
  name: prime-update-rpc
  namespace: primecloud
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#    service.beta.kubernetes.io/aws-load-balancer-name: "primecloud-nlb"
#    service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
#    metallb.universe.tf/allow-shared-ip: "172.24.2.78"
spec:
  type: LoadBalancer
  ports:
  - port: 9931
    name: prime-update-rpc
  selector:
    app: prime-update-server

