apiVersion: v1
kind: Service
metadata:
  labels:
    app: bdms-service
  name: bdms-service
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 6969
      targetPort: 9000
  selector:
    app: bdms-service
