apiVersion: v1
kind: Service
metadata:
  labels:
    app: bpm-admin-ui
  name: bpm-admin-ui
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 8096
      targetPort: 8080
  selector:
    app: bpm-admin-ui
