apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-model-admin-ui
  name: data-model-admin-ui
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 8094
      targetPort: 8080
  selector:
    app: data-model-admin-ui
