apiVersion: v1
kind: Service
metadata:
  labels:
    app: acx-merkle
  name: acx-merkle-rest-service
  namespace: ops360
spec:
  ports:
  - name: http
    port: 1080
    protocol: TCP
    targetPort: 1080
  selector:
    app: acx-merkle
  type: ClusterIP
