apiVersion: v1
kind: Service
metadata:
  labels:
    app: uoi-pipe 
  name: uoi-pipe
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9105 
      targetPort: 9105
  selector:
    app: uoi-pipe
