apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dp-ingestion-service
  name: dp-ingestion-service
  namespace: uat01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-ingestion-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dp-ingestion-service
    spec:
      containers:
        - name: dp-ingestion-service
          image: ac-m2repo-prod:5000/ac-data-update-monitor/ingestion-service:latest 
          env:
            - name: CASSANDRA_HOSTS
              value: "cassandra1.uat.acx-sandbox.net"
          ports:
            - containerPort: 9000
      restartPolicy: Always
