apiVersion: v1
kind: Service
metadata:
  labels:
    app: dp-read-service
  name: dp-read-service
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9000
  selector:
    app: dp-read-service
