apiVersion: v1
kind: Service
metadata:
  labels:
    app: mapping-service 
  name: mapping-service
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9018
      targetPort: 9000        
  selector:
    app: mapping-service

