apiVersion: v1
kind: Service
metadata:
  labels:
    app: issue-service
  name: issue-service
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9021
      targetPort: 9000
  selector:
    app: issue-service

