apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-service-ui
  name: task-service-ui
  namespace: uat01
spec:
  ports:
    - name: http
      port: 8097
      targetPort: 8080
  selector:
    app: task-service-ui
