apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-service
  namespace: uat01
  name: task-service
spec:
  ports:
    - name: http
      port: 9012
      targetPort: 9000 
  selector:
    app: task-service
