---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wfe-pvc
  namespace: uat01
spec:
  storageClassName: nfs-uat01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-wfe
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: interfaces-pvc
  namespace: uat01
spec:
  storageClassName: nfs-uat01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-interfaces
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lineage-queue-pvc
  namespace: uat01
spec:
  storageClassName: nfs-uat01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-lineage-queue
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lineage-fails-pvc
  namespace: uat01
spec:
  storageClassName: nfs-uat01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-lineage-fails
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ac-select-fetcher-pvc
  namespace: uat01
spec:
  storageClassName: nfs-uat01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-ac-select-fetcher

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: batch-publisher-pvc
  namespace: uat01
spec:
  storageClassName: nfs-uat01
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-batch-publisher

