apiVersion: v1
kind: Service
metadata:
  labels:
    app: alpha-stream-converter 
  name: alpha-stream-converter
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9023 
      targetPort: 9000
  selector:
    app: alpha-stream-converter
