apiVersion: v1
kind: Service
metadata:
  labels:
    app: batch-publisher-ui
  name: batch-publisher-ui
  namespace: uat01
spec:
  ports:
    - name: http
      port: 8080 
  selector:
    app: batch-publisher-ui

