apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: batch-publisher
  name: batch-publisher
  namespace: uat01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: batch-publisher
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: batch-publisher
    spec:
      containers:
        - name: batch-publisher
          image: ac-m2repo-prod:5000/acx-batch-publisher-service:1.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: COOKIE_SECRETS
              valueFrom:
                secretKeyRef:
                  name: batch-publisher-auth-token
                  key: token
            - name: APPLICATION_SECRET
              value: "2d8792eab-bc2a-4c44-8bf6-74fc234934b1e16"
            - name: ALLOWED_HOSTS
              value: "."
            - name: BDM_SERVICE_URL
              value: http://bdms-service.uat01.svc.cluster.local:6969/ac
            - name: DATASETS_SERVICE_URL
              value: "http://data-sets-service.uat01.svc.cluster.local:9011"
            - name: PROCESS_TRACKING_SERVICE_URL
              value: "http://process-tracking.uat01.svc.cluster.local:8090/api/v1/process"
            - name: CASSANDRA_HOST
              value: "cassandra1.uat.acx-sandbox.net"
            - name: CASSANDRA_PORT
              value: "9042"
            - name: CASSANDRA_DATA_CENTER
              value: "us-east"
            - name: CASSANDRA_AWS_KEYSPACES
              value: "false"
            - name: CASSANDRA_AWS_SIGV4
              value: "false"
            - name: CASSANDRA_KEYSPACE
              value: "ops360uat01_batch_publisher"
            - name: CASSANDRA_CREATE_SCHEMA
              value: "true"
            - name: CASSANDRA_SCHEMA_FILE
              value: "db/schema.cql"
            - name: USE_QUERY_OPTIONS
              value: "true"
            - name: COOKIE_FILE
              value: "cookies.txt.ac"

          ports:
            - containerPort: 9000 
              name: http

          volumeMounts:
            - mountPath: /home/user/app/db/schema.cql
              name: batch-publisher-configmap-volume
              subPath: schema.cql

            - mountPath: /home/user/app/data
              name: nfspathshare-batch-publisher

      restartPolicy: Always

      volumes:
        - name: batch-publisher-configmap-volume
          configMap:
            name: batch-publisher
            items:
              - key: schema.cql
                path: schema.cql

        - name: nfspathshare-batch-publisher
          persistentVolumeClaim:
            claimName: batch-publisher-pvc        
