apiVersion: v1
kind: Service
metadata:
  labels:
    app: batch-publisher
  name: batch-publisher
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9017
      targetPort: 9000        
  selector:
    app: batch-publisher

