apiVersion: v1
kind: Service
metadata:
  labels:
    app: lineage-stats
  name: lineage-stats
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9014
      targetPort: 9000
  selector:
    app: lineage-stats
