apiVersion: v1
kind: Service
metadata:
  labels:
    app: lineage-stats-ui
  name: lineage-stats-ui
  namespace: uat01 
spec:
  ports:
    - name: http
      port: 8098
      targetPort: 8080
  selector:
    app: lineage-stats-ui
