apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  namespace: primecloud
spec:
  ports:
  - port: 9864
    name: hdfs-datanode-http
  - port: 9866
    name: hdfs-datanode-meta
  selector:
    app: hdfs-datanode
