apiVersion: v1
kind: Service
metadata:
  labels:
    app: process-tracking
  name: process-tracking
  namespace: uat01
spec:
  ports:
    - name: http
      port: 8090
      targetPort: 8080
  selector:
    app: process-tracking
