apiVersion: v1
kind: Service
metadata:
  labels:
    app: acx-streaming
  name: acx-streaming-service
  namespace: ops360
spec:
  ports:
  - name: http
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: acx-streaming
  type: LoadBalancer
