apiVersion: v1
kind: Service
metadata:
  labels:
    cache-service: hazelcast
  name: acx-hazelcast-member-service
  namespace: ops360 
spec:
  ports:
  - name: hazelcast-0
    port: 5701
    protocol: TCP
    targetPort: 5701
  - name: hazelcast-1
    port: 5702
    protocol: TCP
    targetPort: 5702
  - name: hazelcast-2
    port: 5703
    protocol: TCP
    targetPort: 5703
  - name: hazelcast-3
    port: 5704
    protocol: TCP
    targetPort: 5704
  - name: hazelcast-4
    port: 5705
    protocol: TCP
    targetPort: 5705
  selector:
    cache-service: hazelcast

