apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-sets-service
  name: data-sets-service
  namespace: uat01
spec:
  ports:
    - name: http
      port: 9011
      targetPort: 9000
  selector:
    app: data-sets-service
