apiVersion: v1
kind: Service
metadata:
  labels:
    app: acx-rest
  name: acx-rest-service
  namespace: ops360
spec:
  ports:
  - name: http
    port: 9000 
    protocol: TCP
    targetPort: 9000 
  selector:
    app: acx-rest
  type: ClusterIP

