apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-primecloud #IMPORTANT pvc needs to mention this name
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: gp2 
  fsType: ext4 
