---
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-credentials
  namespace: ops360
type: Opaque
stringData:
  username: cassandra
  password: cassandra

---
#used by acx-auth-rest

apiVersion: v1
kind: Secret
metadata:
  name: acx-auth-rest
  namespace: ops360
type: Opaque
stringData:
  serviceadapter.conf: | 
    // AC Plus host
    host="prime.poc-demo.alveo-sandbox.net"
    // AC Plus installation name
    installationName="AC 7.4"
    // AC Plus user - probably admin to be able to check authentications
    // and authorizations
    username="acdba"
    // AC Plus user password
    password="welcome"
    // the number of concurrent queries that we can submit to the server
    // an internal semaphore in auth is controlling access
    concurrentQueriesCount=8
    // optional argument which provides the String passed
    // as arguments to acService::setNodes (bypassing default
    // scanning behavior) - uncommed the line below if needed and
    // set its value appropriately
    optionalSetNodesTo="UPDATE:536870931,QUERY:536870932"

  signatureservice.conf: | 
    // the name (standard) of the HMAC algorithm
    algorithmName="HS512"
    // the signature key
    key=TEST_SIGNATURE

  signatureverificationservice.conf: | 
    // the signature key - the algo is expected in JWT
    key=TEST_SIGNATURE

---
#used by acx-merkle

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: ops360
type: Opaque
stringData:
  signature_key: TEST_SIGNATURE

---
#used by acx-fastapi

apiVersion: v1
kind: Secret
metadata:
  name: streaming-credentials
  namespace: ops360
type: Opaque
stringData:
  username: streamer
  password: streamerpass

---

#used by acx-plus

apiVersion: v1
kind: Secret
metadata:
  name: merkle-credentials
  namespace: ops360
type: Opaque
stringData:
  username: merkler
  password: merklerpass
