
apiVersion: v1
kind: ConfigMap
metadata: 
  name: database-init
  namespace: ops360
data: 
  log4j2.xml: |-
      <?xml version="1.0" encoding="UTF-8"?>
      <Configuration status="warn" name="MyApp" packages="">
        <Appenders>
          <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
              <PatternLayout pattern="%X{event.id} %d{yyyy-MM-dd HH:mm:ss} [%.30t] %-5p %c{1}:%L - %m%n" />
          </Console>
        </Appenders>
        <Loggers>
          <Logger name="httpclient.wire" level="OFF" additivity="false" />
          <Logger name="com.netflix" level="INFO" />
          <Logger name="com.ac.publisher.model.merkle" level="DEBUG" />
          <Logger name="com.assetcontrol.acx.persistence.cassandra.data.TimeSeriesInfoDao" level="DEBUG" />
          <Logger name="log4j.logger.com.assetcontrol.acx.integration.plus.tm.nodegroup.kafka" level="INFO" />
          <Logger name="log4j.logger.com.assetcontrol.acx.integration.plus.tm" level="INFO" />
          <!-- avoid recursive logging -->
          <Logger name="org.apache.kafka" level="WARN" />
          <Root level="${env:LOG_LEVEL:-INFO}">
            <AppenderRef ref="STDOUT" />
          </Root>
        </Loggers>
      </Configuration>

